# ===================================
#  Form Behavior Config
# ===================================

name: 'redmarlin.faq::lang.common.category'
form: ~/plugins/redmarlin/faq/models/category/fields.yaml
modelClass: RedMarlin\Faq\Models\Category
defaultRedirect: redmarlin/faq/categories

create:
    title: 'redmarlin.faq::lang.titles.category.create'
    redirect: redmarlin/faq/categories/update/:id
    redirectClose: redmarlin/faq/categories
    flashSave: 'redmarlin.faq::lang.titles.category.added'

update:
    title: 'redmarlin.faq::lang.titles.category.update'
    redirect: redmarlin/faq/categories
    redirectClose: redmarlin/faq/categories
    flashSave: 'redmarlin.faq::lang.titles.category.saved'
    flashDelete: 'redmarlin.faq::lang.titles.category.deleted'
