# ===================================
#  List Behavior Config
# ===================================

title: 'redmarlin.faq::lang.titles.category.list'
list: ~/plugins/redmarlin/faq/models/category/columns.yaml
modelClass: RedMarlin\Faq\Models\Category
recordUrl: redmarlin/faq/categories/update/:id
recordsPerPage: 20
showSetup: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
