# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: 'redmarlin.faq::lang.titles.question.reorder'

# Attribute name
nameFrom: question

# Model Class name
modelClass: RedMarlin\Faq\Models\Question

# Toolbar widget configuration
toolbar: