# ===================================
#  List Behavior Config
# ===================================

title: 'redmarlin.faq::lang.titles.question.list'
list: ~/plugins/redmarlin/faq/models/question/columns.yaml
modelClass: RedMarlin\Faq\Models\Question
recordUrl: redmarlin/faq/questions/update/:id
recordsPerPage: 20
showSetup: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
