# ===================================
#  Form Behavior Config
# ===================================

name: 'redmarlin.faq::lang.common.question'
form: ~/plugins/redmarlin/faq/models/question/fields.yaml
modelClass: RedMarlin\Faq\Models\Question
defaultRedirect: redmarlin/faq/questions

create:
    title: 'redmarlin.faq::lang.titles.question.create'
    redirect: redmarlin/faq/questions/update/:id
    redirectClose: redmarlin/faq/questions
    flashSave: 'redmarlin.faq::lang.titles.question.added'

update:
    title: 'redmarlin.faq::lang.titles.question.update'
    redirect: redmarlin/faq/questions
    redirectClose: redmarlin/faq/questions
    flashSave: 'redmarlin.faq::lang.titles.question.saved'
    flashDelete: 'redmarlin.faq::lang.titles.question.deleted'